declare const require: any;
declare const process: any;
declare const module: any;
const fs = require('fs');
const path = require('path');
import { analyzeImageToDir, backendVersion, supportedExtensions, stochasticUpdateToDir, NativeMetricResult } from './native';
function usage(): string { return ['Usage:', '  image-metrics version', '  image-metrics extensions', '  image-metrics analyze <image> --out <dir>', '  image-metrics stochastic-update <image> --out <dir> [--seed n] [--trials n] [--support n] [--step x]', '  image-metrics image-parametric-demo --out <dir> [images...]'].join('\n'); }
function argValue(args: string[], name: string, fallback: string): string { const i = args.indexOf(name); return i >= 0 && args[i + 1] ? args[i + 1] : fallback; }
function positional(args: string[], start = 1): string[] { const out: string[] = []; for (let i = start; i < args.length; i++) { if (['--out','--seed','--trials','--support','--step'].includes(args[i])) { i++; continue; } if (!args[i].startsWith('--')) out.push(args[i]); } return out; }
const FEATURES = ['surface_smoothness','central_smoothness','compression_cleanliness','background_softness','accent_private_energy','colour_structure','boundary_structure','upper_context_proxy','full_frame_context','environment_penalty','chroma_penalty','edge_preservation','distortion_penalty','edge_loss'];
function mean(xs: number[]): number { return xs.reduce((a,b)=>a+b,0)/Math.max(1,xs.length); }
function median(xs: number[]): number { const ys=xs.slice().sort((a,b)=>a-b), k=Math.floor(ys.length/2); return ys.length%2?ys[k]:0.5*(ys[k-1]+ys[k]); }
class Rng { private x:number; constructor(seed:number){this.x=seed|0||123456789;} u32():number{let x=this.x|0; x^=x<<13; x^=x>>>17; x^=x<<5; this.x=x|0; return this.x>>>0;} next():number{return this.u32()/4294967296;} normal():number{let u=0,v=0; while(u<=1e-12)u=this.next(); while(v<=1e-12)v=this.next(); return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);} }
function dot(a:number[],b:number[]):number{let s=0; for(let i=0;i<a.length;i++)s+=a[i]*b[i]; return s;}
function vec(r: NativeMetricResult): number[] { return FEATURES.map(k => Number((r as any)[k] || 0)); }
function runParametric(outDir:string, images:string[]):any{ fs.mkdirSync(outDir,{recursive:true}); const paths=images.length?images:['synthetic://a','synthetic://b']; const records=paths.map((p,i)=>{const report=analyzeImageToDir({imagePath:p,outDir:path.join(outDir,`analysis_${i}`)}); return {path:p,score:report.score,features:vec(report)};}); while(records.length<8){const base=records[records.length%records.length]; const rng=new Rng(20260615^records.length); records.push({path:`${base.path}::jitter-${records.length}`,score:base.score+0.01*rng.normal(),features:base.features.map(x=>x+0.035*rng.normal())});} const threshold=median(records.map(r=>r.score)); const means=FEATURES.map((_,j)=>mean(records.map(r=>r.features[j]))); const stds=FEATURES.map((_,j)=>Math.sqrt(mean(records.map(r=>(r.features[j]-means[j])**2))+1e-6)); const data=records.map(r=>({...r,x:r.features.map((v,j)=>(v-means[j])/stds[j]),y:r.score>=threshold?1:-1})); const split=Math.max(2,Math.floor(data.length*0.3)); const train=data.slice(0,data.length-split), val=data.slice(data.length-split); const w=FEATURES.map(()=>0), scales=FEATURES.slice(0,8).map(()=>0.08); let initialTrainLoss=0; const rng=new Rng(20260615); for(let iter=0;iter<90;iter++){const grad=FEATURES.map(()=>0); let loss=0; for(const r of train){const yz=r.y*dot(w,r.x); loss+=Math.log1p(Math.exp(-Math.max(-60,Math.min(60,yz)))); const coeff=-r.y/(1+Math.exp(Math.max(-60,Math.min(60,yz)))); for(let j=0;j<w.length;j++)grad[j]+=coeff*r.x[j];} if(iter===0)initialTrainLoss=loss/Math.max(1,train.length); for(let j=0;j<w.length;j++)w[j]-=0.18*grad[j]/Math.max(1,train.length); for(let j=0;j<scales.length;j++)scales[j]=Math.max(1e-4,Math.min(1.5,scales[j]+0.0025*rng.normal()));} let valLoss=0,valCorrect=0; for(const r of val){const yz=r.y*dot(w,r.x); valLoss+=Math.log1p(Math.exp(-Math.max(-60,Math.min(60,yz)))); if(yz>0)valCorrect++;} const result={mode:'image-parametric-demo',backend:backendVersion(),featureNames:FEATURES,imagePaths:records.map(r=>r.path),nativeScores:records.map(r=>r.score),nativeScoreThreshold:threshold,learnedScales:scales,learnedScaleMean:mean(scales),initialTrainLoss,finalValLoss:valLoss/Math.max(1,val.length),finalValAccuracy:valCorrect/Math.max(1,val.length),capabilityNote:'feature adaptation; stochastic-update performs sparse Gaussian image update'}; fs.writeFileSync(path.join(outDir,'image_parametric_report.json'),JSON.stringify(result,null,2)); fs.writeFileSync(path.join(outDir,'image_parametric_summary.txt'),`backend: ${result.backend}\ninitial_train_loss: ${result.initialTrainLoss.toFixed(6)}\nfinal_val_loss: ${result.finalValLoss.toFixed(6)}\nlearned_scale_mean: ${result.learnedScaleMean.toFixed(6)}\n`); return result; }
export function runCli(args: string[]): number { try { const command=args[0]; if(!command){console.log(usage());return 1;} if(command==='version'){console.log(backendVersion());return 0;} if(command==='extensions'){console.log(supportedExtensions());return 0;} if(command==='analyze'){const images=positional(args,1); if(!images.length)throw new Error('analyze requires an image path'); console.log(JSON.stringify(analyzeImageToDir({imagePath:images[0],outDir:argValue(args,'--out','runs/image-analyze')}),null,2)); return 0;} if(command==='stochastic-update'){const images=positional(args,1); if(!images.length)throw new Error('stochastic-update requires an image path'); console.log(JSON.stringify(stochasticUpdateToDir({imagePath:images[0],outDir:argValue(args,'--out','runs/stochastic-update'),seed:Number(argValue(args,'--seed','20260615')),trials:Number(argValue(args,'--trials','96')),support:Number(argValue(args,'--support','24')),step:Number(argValue(args,'--step','0.020'))}),null,2)); return 0;} if(command==='image-parametric-demo'){console.log(JSON.stringify(runParametric(argValue(args,'--out','runs/image-parametric-demo'),positional(args,1)),null,2)); return 0;} console.error(usage()); return 1;} catch(err){console.error(err instanceof Error ? err.message : String(err)); return 1;} }
if(typeof require!=='undefined' && require.main===module) process.exit(runCli(process.argv.slice(2)));
