declare const require: any;
declare const Buffer: any;
const fs = require('fs');
const path = require('path');

interface Frame { w: number; h: number; rgb: Float64Array; }
interface Params { smooth: number; levels: number; ink: number; saturation: number; warmth: number; brightness: number; alpha: number; }
interface Mask { name: string; weights: Float64Array; }
interface Metrics { score: number; paired_fidelity: number; edge_alignment: number; style_score: number; content_retention: number; continuity: number; skin_continuity: number; silhouette_continuity: number; visible_progress: number; artifact_penalty: number; bitshard_penalty: number; occlusion_penalty: number; color_loss: number; edge_loss: number; hard_reject: boolean; reject_reason: string; }
interface TrialTrace { trial: number; update_kind: string; metrics: Metrics; params: Params; accepted_candidate: boolean; }
export interface TrainStyleModelRequest { sourcePath: string; targetPath: string; negativePath?: string; outDir: string; seed: number; epochs: number; trials: number; strength: number; }

class Rng { private x: number; constructor(seed: number) { this.x = seed | 0 || 123456789; } u32(): number { let x = this.x | 0; x ^= x << 13; x ^= x >>> 17; x ^= x << 5; this.x = x | 0; return this.x >>> 0; } next(): number { return this.u32() / 4294967296; } normal(): number { let u = 0, v = 0; while (u <= 1e-12) u = this.next(); while (v <= 1e-12) v = this.next(); return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v); } }
function clamp01(x: number): number { return Number.isFinite(x) ? Math.max(0, Math.min(1, x)) : 0; }
function round6(x: number): number { return Math.round(x * 1000000) / 1000000; }
function byte(x: number): number { return Math.max(0, Math.min(255, Math.round(clamp01(x) * 255))); }
function idx(f: Frame, x: number, y: number, c: number): number { return ((y * f.w + x) * 3) + c; }
function px(w: number, x: number, y: number): number { return y * w + x; }
function ensureDir(p: string): void { fs.mkdirSync(p, { recursive: true }); }
function clone(f: Frame): Frame { return { w: f.w, h: f.h, rgb: new Float64Array(f.rgb) }; }
function add(a: Params, b: Params): Params { return { smooth: a.smooth + b.smooth, levels: a.levels + b.levels, ink: a.ink + b.ink, saturation: a.saturation + b.saturation, warmth: a.warmth + b.warmth, brightness: a.brightness + b.brightness, alpha: a.alpha + b.alpha }; }
function bound(p: Params): Params { return { smooth: Math.max(0, Math.min(6, p.smooth)), levels: Math.max(3, Math.min(9, p.levels)), ink: Math.max(0, Math.min(3.2, p.ink)), saturation: Math.max(0.55, Math.min(1.75, p.saturation)), warmth: Math.max(-1.2, Math.min(1.2, p.warmth)), brightness: Math.max(-0.12, Math.min(0.12, p.brightness)), alpha: Math.max(0.15, Math.min(1, p.alpha)) }; }
function zero(): Params { return { smooth: 0, levels: 0, ink: 0, saturation: 0, warmth: 0, brightness: 0, alpha: 0 }; }
function base(): Params { return { smooth: 1.20, levels: 5.2, ink: 0.92, saturation: 1.04, warmth: 0, brightness: 0, alpha: 0.72 }; }
function mutate(p: Params, rng: Rng, s: number): Params { return bound({ smooth: p.smooth + 0.58 * s * rng.normal(), levels: p.levels + 0.78 * s * rng.normal(), ink: p.ink + 0.20 * s * rng.normal(), saturation: p.saturation + 0.10 * s * rng.normal(), warmth: p.warmth + 0.13 * s * rng.normal(), brightness: p.brightness + 0.016 * s * rng.normal(), alpha: p.alpha + 0.08 * s * rng.normal() }); }

function syntheticFrame(id: string, w = 192, h = 192): Frame { let hash = 2166136261 >>> 0; for (let i = 0; i < id.length; i++) { hash ^= id.charCodeAt(i); hash = Math.imul(hash, 16777619) >>> 0; } const rng = new Rng(hash | 0), rgb = new Float64Array(w * h * 3); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const nx = x / Math.max(1, w - 1), ny = y / Math.max(1, h - 1); const c = Math.exp(-(((nx - .50) ** 2) / .08 + ((ny - .43) ** 2) / .09)); const v = .44 + .28 * nx + .12 * Math.sin(8 * nx + 5 * ny); const p = (y * w + x) * 3; rgb[p] = clamp01(v + .17 * c + .02 * rng.normal()); rgb[p + 1] = clamp01(v + .10 * c + .02 * rng.normal()); rgb[p + 2] = clamp01(v + .06 * c + .02 * rng.normal()); } return { w, h, rgb }; }
function readTokens(buf: any): { tokens: string[]; offset: number } { const tokens: string[] = []; let i = 0; while (i < buf.length && tokens.length < 4) { while (i < buf.length && buf[i] <= 32) i++; if (buf[i] === 35) { while (i < buf.length && buf[i] !== 10) i++; continue; } let s = ''; while (i < buf.length && buf[i] > 32) { s += String.fromCharCode(buf[i]); i++; } if (s) tokens.push(s); } while (i < buf.length && buf[i] <= 32) i++; return { tokens, offset: i }; }
function readPpm(file: string): Frame { const buf = fs.readFileSync(file), p = readTokens(buf); if (p.tokens[0] !== 'P6') throw new Error('PPM reader only supports P6'); const w = Number(p.tokens[1]), h = Number(p.tokens[2]), maxv = Number(p.tokens[3]); const rgb = new Float64Array(w * h * 3); for (let i = 0; i < rgb.length; i++) rgb[i] = Number(buf[p.offset + i] || 0) / maxv; return { w, h, rgb }; }
function readBmp(file: string): Frame { const buf = fs.readFileSync(file); if (buf[0] !== 0x42 || buf[1] !== 0x4d) throw new Error('invalid BMP header'); const off = buf.readUInt32LE(10), w = buf.readInt32LE(18), rawH = buf.readInt32LE(22), h = Math.abs(rawH), bpp = buf.readUInt16LE(28); if (bpp !== 24) throw new Error('BMP reader only supports 24-bit BMP'); const row = Math.floor((w * 3 + 3) / 4) * 4, rgb = new Float64Array(w * h * 3); for (let y = 0; y < h; y++) { const sy = rawH > 0 ? h - 1 - y : y; for (let x = 0; x < w; x++) { const s = off + sy * row + x * 3, d = (y * w + x) * 3; rgb[d] = Number(buf[s + 2]) / 255; rgb[d + 1] = Number(buf[s + 1]) / 255; rgb[d + 2] = Number(buf[s]) / 255; } } return { w, h, rgb }; }
function readFrame(p: string): Frame { if (p.startsWith('synthetic://')) return syntheticFrame(p); const ext = path.extname(p).toLowerCase(); if (ext === '.ppm') return readPpm(p); if (ext === '.bmp') return readBmp(p); throw new Error('train-style-model supports synthetic://, .ppm, and 24-bit .bmp inputs'); }
function resize(f: Frame, w: number, h: number): Frame { const rgb = new Float64Array(w * h * 3); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const sx = Math.min(f.w - 1, Math.round(x * (f.w - 1) / Math.max(1, w - 1))), sy = Math.min(f.h - 1, Math.round(y * (f.h - 1) / Math.max(1, h - 1))); for (let c = 0; c < 3; c++) rgb[(y * w + x) * 3 + c] = f.rgb[idx(f, sx, sy, c)]; } return { w, h, rgb }; }
function writeBmp(file: string, f: Frame): void { const row = Math.floor((f.w * 3 + 3) / 4) * 4, dataSize = row * f.h, header = Buffer.alloc(54); header[0] = 0x42; header[1] = 0x4d; header.writeUInt32LE(54 + dataSize, 2); header.writeUInt32LE(54, 10); header.writeUInt32LE(40, 14); header.writeInt32LE(f.w, 18); header.writeInt32LE(f.h, 22); header.writeUInt16LE(1, 26); header.writeUInt16LE(24, 28); header.writeUInt32LE(dataSize, 34); const body = Buffer.alloc(dataSize); for (let y = 0; y < f.h; y++) { const dy = f.h - 1 - y; for (let x = 0; x < f.w; x++) { const s = (y * f.w + x) * 3, d = dy * row + x * 3; body[d] = byte(f.rgb[s + 2]); body[d + 1] = byte(f.rgb[s + 1]); body[d + 2] = byte(f.rgb[s]); } } fs.writeFileSync(file, Buffer.concat([header, body])); }
function writePpm(file: string, f: Frame): void { const h = Buffer.from(`P6\n${f.w} ${f.h}\n255\n`, 'ascii'), b = Buffer.alloc(f.w * f.h * 3); for (let i = 0; i < b.length; i++) b[i] = byte(f.rgb[i]); fs.writeFileSync(file, Buffer.concat([h, b])); }

function lum(f: Frame, x: number, y: number): number { const i = idx(f, Math.max(0, Math.min(f.w - 1, x)), Math.max(0, Math.min(f.h - 1, y)), 0); return .299 * f.rgb[i] + .587 * f.rgb[i + 1] + .114 * f.rgb[i + 2]; }
function edgeAt(f: Frame, x: number, y: number): number { const l = lum(f, x, y); return Math.abs(l - lum(f, x - 1, y)) + Math.abs(l - lum(f, x, y - 1)); }
function skinLikelihood(f: Frame, x: number, y: number): number { const i = idx(f, x, y, 0), r = f.rgb[i], g = f.rgb[i + 1], b = f.rgb[i + 2], l = .299 * r + .587 * g + .114 * b, ch = Math.max(r, g, b) - Math.min(r, g, b); return r > .25 && g > .16 && b > .10 && r > b * 1.03 && r > g * .82 && ch > .025 && ch < .52 && l > .18 && l < .96 ? clamp01((l - .16) / .44) : 0; }
function masks(f: Frame): Mask[] { const names = ['whole','skin','chest_upper_torso','garment','legs','background'], m: Record<string, Float64Array> = {}; for (const n of names) m[n] = new Float64Array(f.w * f.h); for (let y = 0; y < f.h; y++) for (let x = 0; x < f.w; x++) { const p = px(f.w, x, y), nx = x / Math.max(1, f.w - 1), ny = y / Math.max(1, f.h - 1), sw = skinLikelihood(f, x, y); const i = idx(f, x, y, 0), r = f.rgb[i], g = f.rgb[i + 1], b = f.rgb[i + 2], ch = Math.max(r, g, b) - Math.min(r, g, b); m.whole[p] = 1; m.skin[p] = sw; m.chest_upper_torso[p] = sw * (nx > .28 && nx < .72 && ny > .24 && ny < .55 ? 1 : 0); m.legs[p] = sw * (ny > .52 ? 1 : 0); m.garment[p] = ch > .18 || b > r * 1.08 || (r > .55 && b > .45 && g < .52) ? 1 : 0; m.background[p] = sw < .1 && m.garment[p] < .4 ? .75 : 0; } return names.map(name => ({ name, weights: m[name] })); }
function blur(f: Frame, passes: number): Frame { let out = clone(f); for (let pass = 0; pass < passes; pass++) { const src = new Float64Array(out.rgb); for (let y = 0; y < f.h; y++) for (let x = 0; x < f.w; x++) for (let c = 0; c < 3; c++) { let s = 0, n = 0; for (let yy = -1; yy <= 1; yy++) for (let xx = -1; xx <= 1; xx++) { const sx = Math.max(0, Math.min(f.w - 1, x + xx)), sy = Math.max(0, Math.min(f.h - 1, y + yy)), k = xx === 0 && yy === 0 ? 4 : (xx === 0 || yy === 0 ? 2 : 1); s += k * src[idx(f, sx, sy, c)]; n += k; } out.rgb[idx(f, x, y, c)] = s / n; } } return out; }
function transform(f: Frame, p0: Params, target: Frame): Frame { const p = bound(p0), sm = blur(f, Math.round(p.smooth)), out = clone(f), levels = Math.max(2, Math.round(p.levels)); for (let y = 0; y < f.h; y++) for (let x = 0; x < f.w; x++) { const j = idx(f, x, y, 0), e = Math.min(1, 4 * edgeAt(f, x, y)), l = lum(sm, x, y); for (let c = 0; c < 3; c++) { const post = Math.round(sm.rgb[j + c] * (levels - 1)) / (levels - 1); let v = l + (post - l) * p.saturation + p.brightness; v += .08 * p.alpha * (target.rgb[j + c] - v); if (c === 0) v += .030 * p.warmth; if (c === 2) v -= .022 * p.warmth; out.rgb[j + c] = clamp01(v * (1 - .50 * p.ink * e)); } } return out; }
function applyMask(baseFrame: Frame, cand: Frame, m: Mask, alpha: number): Frame { const out = clone(baseFrame); for (let i = 0; i < baseFrame.w * baseFrame.h; i++) { const a = clamp01(m.weights[i] * alpha); out.rgb[i * 3] = clamp01((1 - a) * baseFrame.rgb[i * 3] + a * cand.rgb[i * 3]); out.rgb[i * 3 + 1] = clamp01((1 - a) * baseFrame.rgb[i * 3 + 1] + a * cand.rgb[i * 3 + 1]); out.rgb[i * 3 + 2] = clamp01((1 - a) * baseFrame.rgb[i * 3 + 2] + a * cand.rgb[i * 3 + 2]); } return out; }

function evaluate(candidate: Frame, previous: Frame, source: Frame, target: Frame, negative: Frame | undefined, mask: Mask, inputMetrics?: Metrics): Metrics { let ws = 0, color = 0, edge = 0, content = 0, progress = 0, localJump = 0, skinBreak = 0, silhouetteBreak = 0, occlusion = 0, shard = 0, negGain = 0, sl = 0, sl2 = 0, styleEdge = 0; const bins: Record<string, number> = {}; for (let y = 0; y < candidate.h; y++) for (let x = 0; x < candidate.w; x++) { const w = mask.weights[px(candidate.w, x, y)]; if (w <= 1e-6) continue; const i = idx(candidate, x, y, 0), r = candidate.rgb[i], g = candidate.rgb[i + 1], b = candidate.rgb[i + 2]; const ti = idx(target, x, y, 0), si = idx(source, x, y, 0), pi = idx(previous, x, y, 0); const l = .299 * r + .587 * g + .114 * b, ch = Math.max(r, g, b) - Math.min(r, g, b), e = edgeAt(candidate, x, y), te = edgeAt(target, x, y), se = edgeAt(source, x, y); const cd = (Math.abs(r - target.rgb[ti]) + Math.abs(g - target.rgb[ti + 1]) + Math.abs(b - target.rgb[ti + 2])) / 3; const sd = (Math.abs(r - source.rgb[si]) + Math.abs(g - source.rgb[si + 1]) + Math.abs(b - source.rgb[si + 2])) / 3; const pd = (Math.abs(r - previous.rgb[pi]) + Math.abs(g - previous.rgb[pi + 1]) + Math.abs(b - previous.rgb[pi + 2])) / 3; color += w * cd; edge += w * Math.abs(e - te); content += w * sd; progress += w * pd; localJump += w * Math.max(0, e - Math.max(te, se) - .08); const sourceSkin = skinLikelihood(source, x, y), candSkin = skinLikelihood(candidate, x, y); if ((mask.name === 'skin' || mask.name === 'chest_upper_torso' || mask.name === 'legs') && sourceSkin > .35) { skinBreak += w * Math.max(0, sourceSkin - candSkin); occlusion += w * (cd > .24 && ch > .25 ? 1 : 0); }
      const fg = mask.name === 'whole' || mask.name === 'skin' || mask.name === 'chest_upper_torso' || mask.name === 'garment' || mask.name === 'legs'; if (fg && sd > .34 && cd > .22) silhouetteBreak += w; const cyanMagenta = (b > .55 && g > .42 && r < .35) || (r > .55 && b > .45 && g < .35); if ((cyanMagenta || ch > .52) && e > .045 && sd > .18) shard += w; if (negative) { const nd = (Math.abs(r - negative.rgb[i]) + Math.abs(g - negative.rgb[i + 1]) + Math.abs(b - negative.rgb[i + 2])) / 3; const snd = (Math.abs(source.rgb[si] - negative.rgb[i]) + Math.abs(source.rgb[si + 1] - negative.rgb[i + 1]) + Math.abs(source.rgb[si + 2] - negative.rgb[i + 2])) / 3; negGain += w * Math.max(0, snd - nd); } sl += w * l; sl2 += w * l * l; styleEdge += w * e; bins[`${Math.round(r * 6)}:${Math.round(g * 6)}:${Math.round(b * 6)}`] = 1; ws += w; }
  const z = Math.max(1e-9, ws), mean = sl / z, variance = Math.max(0, sl2 / z - mean * mean), palette = Object.keys(bins).length / Math.max(1, Math.round(z)); const colorLoss = color / z, edgeLoss = edge / z, contentLoss = content / z, progressLoss = progress / z; const paired = clamp01(1 - colorLoss / .34), edgeAlign = clamp01(1 - edgeLoss / .13), retention = clamp01(1 - contentLoss / .48), visible = clamp01(progressLoss / .020); const flatness = clamp01(1 - variance / .060), paletteComp = clamp01(1 - palette / .22), line = clamp01((styleEdge / z) / .11); const continuity = clamp01(1 - (localJump / z) / .10), skinCont = clamp01(1 - (skinBreak / z) / .42), silhouetteCont = clamp01(1 - (silhouetteBreak / z)); const bitPenalty = clamp01((shard / z) + (negGain / z) * .65), occPenalty = clamp01((occlusion / z) + (skinBreak / z) * .45), artifact = clamp01((localJump / z) * 2.2 + bitPenalty * .85 + occPenalty * .75 + (silhouetteBreak / z) * .70); let score = .30 * paired + .18 * edgeAlign + .15 * retention + .12 * flatness + .10 * paletteComp + .07 * line + .05 * continuity + .05 * skinCont + .04 * silhouetteCont + .04 * visible - .42 * artifact - .28 * bitPenalty - .24 * occPenalty; let reject = false, reason = ''; if (inputMetrics) { if (bitPenalty > inputMetrics.bitshard_penalty + .045) { reject = true; reason = 'bitshard_penalty_growth'; } else if (occPenalty > inputMetrics.occlusion_penalty + .060) { reject = true; reason = 'occlusion_penalty_growth'; } else if (skinCont < inputMetrics.skin_continuity - .060) { reject = true; reason = 'skin_continuity_loss'; } else if (silhouetteCont < inputMetrics.silhouette_continuity - .050) { reject = true; reason = 'silhouette_continuity_loss'; } else if (visible < .10 && paired < .92) { reject = true; reason = 'no_visible_progress'; } }
  if (reject) score -= 1.0; return { score: round6(score), paired_fidelity: round6(paired), edge_alignment: round6(edgeAlign), style_score: round6(.25 * flatness + .25 * paletteComp + .25 * line + .25 * edgeAlign), content_retention: round6(retention), continuity: round6(continuity), skin_continuity: round6(skinCont), silhouette_continuity: round6(silhouetteCont), visible_progress: round6(visible), artifact_penalty: round6(artifact), bitshard_penalty: round6(bitPenalty), occlusion_penalty: round6(occPenalty), color_loss: round6(colorLoss), edge_loss: round6(edgeLoss), hard_reject: reject, reject_reason: reason }; }

export function trainStyleModelToDir(req: TrainStyleModelRequest): any { ensureDir(req.outDir); const target0 = readFrame(req.targetPath), source = resize(readFrame(req.sourcePath), target0.w, target0.h), target = target0, negative = req.negativePath ? resize(readFrame(req.negativePath), target.w, target.h) : undefined; let current = clone(source); const rng = new Rng(req.seed), model: Record<string, Params> = {}, instance: Record<string, Params> = {}, trace: any[] = []; const baseMasks = masks(source); for (const m of baseMasks) { model[m.name] = base(); instance[m.name] = zero(); }
  for (let epoch = 0; epoch < req.epochs; epoch++) for (const m of baseMasks) { const inputMetrics = evaluate(current, current, source, target, negative, m); let bestMetrics = inputMetrics, bestKind = 'none', bestTrial = -1, bestFrame = current, bestModel = model[m.name], bestInstance = instance[m.name], trials: TrialTrace[] = []; for (let trial = 0; trial < req.trials; trial++) { const scale = Math.max(.18, 1 - trial / Math.max(1, req.trials)); const candModel = mutate(model[m.name], rng, scale), paramsModel = bound(add(candModel, instance[m.name])), frameModel = applyMask(current, transform(current, paramsModel, target), m, req.strength * paramsModel.alpha), metricsModel = evaluate(frameModel, current, source, target, negative, m, inputMetrics); const acceptModel = !metricsModel.hard_reject && metricsModel.score > bestMetrics.score; trials.push({ trial, update_kind: 'model', metrics: metricsModel, params: paramsModel, accepted_candidate: acceptModel }); if (acceptModel) { bestMetrics = metricsModel; bestKind = 'model'; bestTrial = trial; bestFrame = frameModel; bestModel = candModel; bestInstance = instance[m.name]; }
      const candInstance = mutate(instance[m.name], rng, scale), paramsInstance = bound(add(model[m.name], candInstance)), frameInstance = applyMask(current, transform(current, paramsInstance, target), m, req.strength * paramsInstance.alpha), metricsInstance = evaluate(frameInstance, current, source, target, negative, m, inputMetrics); const acceptInstance = !metricsInstance.hard_reject && metricsInstance.score > bestMetrics.score; trials.push({ trial, update_kind: 'instance', metrics: metricsInstance, params: paramsInstance, accepted_candidate: acceptInstance }); if (acceptInstance) { bestMetrics = metricsInstance; bestKind = 'instance'; bestTrial = trial; bestFrame = frameInstance; bestModel = model[m.name]; bestInstance = candInstance; } }
    if (bestKind !== 'none') { model[m.name] = bestModel; instance[m.name] = bestInstance; current = bestFrame; } trace.push({ epoch, region: m.name, input_metrics: inputMetrics, accepted_metrics: bestMetrics, accepted_kind: bestKind, accepted_trial: bestTrial, gain: round6(bestMetrics.score - inputMetrics.score), model_params: model[m.name], instance_params: instance[m.name], trials }); }
  writeBmp(path.join(req.outDir, 'trained_output.bmp'), current); writePpm(path.join(req.outDir, 'trained_output.ppm'), current); fs.writeFileSync(path.join(req.outDir, 'trained_cartoon_model.json'), JSON.stringify({ format: 'LS_TRAINED_CARTOON_MODEL_V2', source: req.sourcePath, target: req.targetPath, negative: req.negativePath, objective: 'paired_fidelity_edge_alignment_continuity_artifact_reject', model }, null, 2)); fs.writeFileSync(path.join(req.outDir, 'trained_instance_params.json'), JSON.stringify({ format: 'LS_TRAINED_CARTOON_INSTANCE_PARAMS_V2', instance }, null, 2)); fs.writeFileSync(path.join(req.outDir, 'training_trace.json'), JSON.stringify(trace, null, 2)); fs.writeFileSync(path.join(req.outDir, 'training_trace.csv'), ['epoch,region,input_score,accepted_score,gain,accepted_kind,accepted_trial,paired_fidelity,edge_alignment,content_retention,continuity,skin_continuity,silhouette_continuity,visible_progress,artifact_penalty,bitshard_penalty,occlusion_penalty', ...trace.map(r => [r.epoch, r.region, r.input_metrics.score, r.accepted_metrics.score, r.gain, r.accepted_kind, r.accepted_trial, r.accepted_metrics.paired_fidelity, r.accepted_metrics.edge_alignment, r.accepted_metrics.content_retention, r.accepted_metrics.continuity, r.accepted_metrics.skin_continuity, r.accepted_metrics.silhouette_continuity, r.accepted_metrics.visible_progress, r.accepted_metrics.artifact_penalty, r.accepted_metrics.bitshard_penalty, r.accepted_metrics.occlusion_penalty].join(','))].join('\n') + '\n'); const finalWhole = evaluate(current, current, source, target, negative, baseMasks[0]); const report = { mode: 'alternating-style-model-training', source: req.sourcePath, target: req.targetPath, negative: req.negativePath, epochs: req.epochs, trials: req.trials, objective: 'paired structural fidelity with no-op and artifact-family rejection', final_metrics: finalWhole, trace_rows: trace.length, outputs: ['trained_output.bmp','trained_cartoon_model.json','trained_instance_params.json','training_trace.json','training_trace.csv'] }; fs.writeFileSync(path.join(req.outDir, 'training_summary.json'), JSON.stringify(report, null, 2)); fs.writeFileSync(path.join(req.outDir, 'training_summary.txt'), `mode: ${report.mode}\nobjective: ${report.objective}\nepochs: ${req.epochs}\ntrials: ${req.trials}\nfinal_score: ${finalWhole.score}\nartifact_penalty: ${finalWhole.artifact_penalty}\nbitshard_penalty: ${finalWhole.bitshard_penalty}\nocclusion_penalty: ${finalWhole.occlusion_penalty}\ntrace_rows: ${trace.length}\n`); return report; }
