declare const require: any; declare const process: any; declare const __dirname: string;
const fs = require('fs'); const path = require('path'); const cp = require('child_process'); const root=path.resolve(__dirname,'..','..');
function run(args:string[]):void{const p=cp.spawnSync(process.execPath,args,{cwd:root,encoding:'utf-8'}); process.stdout.write(p.stdout||''); process.stderr.write(p.stderr||''); if(p.status!==0)throw new Error(`command failed: ${args.join(' ')}`);}
function assertFile(p:string):void{if(!fs.existsSync(p)||fs.statSync(p).size<=0)throw new Error(`missing or empty file: ${p}`);}
const out=path.join(root,'runs','smoke-image-metrics'); fs.rmSync(out,{recursive:true,force:true});
run(['dist/src/cli.js','version']);
run(['dist/src/cli.js','analyze','synthetic://smoke-a','--out',path.join(out,'analyze')]); assertFile(path.join(out,'analyze','report.json')); assertFile(path.join(out,'analyze','feature_fixture.json'));
run(['dist/src/cli.js','image-parametric-demo','--out',path.join(out,'parametric'),'synthetic://smoke-a','synthetic://smoke-b']); assertFile(path.join(out,'parametric','image_parametric_report.json'));
run(['dist/src/cli.js','stochastic-update','synthetic://smoke-a','--out',path.join(out,'update'),'--trials','16','--support','8','--step','0.018']); assertFile(path.join(out,'update','updated.ppm')); assertFile(path.join(out,'update','update_trace.json')); assertFile(path.join(out,'update','support_dictionary.json'));
run(['dist/src/cli.js','convnet-distortion','synthetic://smoke-a','--out',path.join(out,'convnet'),'--seed','20260615','--shallow-strength','0.65','--deep-strength','1.10']); assertFile(path.join(out,'convnet','convnet_report.json')); assertFile(path.join(out,'convnet','shallow_convnet_distortion.bmp')); assertFile(path.join(out,'convnet','shallow_convnet_activation_mask.bmp')); assertFile(path.join(out,'convnet','shallow_convnet_activation_overlay.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_distortion.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_activation_mask.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_high_overlay.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_high_overlay_grid.bmp'));
run(['dist/src/cli.js','fit-transform',path.join(out,'convnet','source.bmp'),path.join(out,'convnet','deeper_convnet_distortion.bmp'),'--out',path.join(out,'fit'),'--seed','20260616','--trials','24','--smoothness-weight','0.05','--edge-weight','0.10','--complexity-weight','0.04']); assertFile(path.join(out,'fit','fit_report.json')); assertFile(path.join(out,'fit','fit_trace.json')); assertFile(path.join(out,'fit','fit_support_dictionary.json')); assertFile(path.join(out,'fit','fit_output.bmp')); assertFile(path.join(out,'fit','fit_residual.bmp'));
console.log('image-metrics sparse Gaussian, TypeScript convnet, and regularized fit-transform smoke passed');
