declare const require: any; declare const process: any; declare const __dirname: string;
const fs = require('fs'); const path = require('path'); const cp = require('child_process'); const root=path.resolve(__dirname,'..','..');
function run(args:string[]):void{const p=cp.spawnSync(process.execPath,args,{cwd:root,encoding:'utf-8'}); process.stdout.write(p.stdout||''); process.stderr.write(p.stderr||''); if(p.status!==0)throw new Error(`command failed: ${args.join(' ')}`);}
function assertFile(p:string):void{if(!fs.existsSync(p)||fs.statSync(p).size<=0)throw new Error(`missing or empty file: ${p}`);}
const out=path.join(root,'runs','smoke-image-metrics'); fs.rmSync(out,{recursive:true,force:true});
run(['dist/src/cli.js','version']);
run(['dist/src/cli.js','analyze','synthetic://smoke-a','--out',path.join(out,'analyze')]); assertFile(path.join(out,'analyze','report.json')); assertFile(path.join(out,'analyze','feature_fixture.json'));
run(['dist/src/cli.js','image-parametric-demo','--out',path.join(out,'parametric'),'synthetic://smoke-a','synthetic://smoke-b']); assertFile(path.join(out,'parametric','image_parametric_report.json'));
run(['dist/src/cli.js','stochastic-update','synthetic://smoke-a','--out',path.join(out,'update'),'--trials','16','--support','8','--step','0.018']); assertFile(path.join(out,'update','updated.ppm')); assertFile(path.join(out,'update','update_trace.json')); assertFile(path.join(out,'update','support_dictionary.json'));
run(['dist/src/cli.js','convnet-distortion','synthetic://smoke-a','--out',path.join(out,'convnet'),'--seed','20260615','--shallow-strength','0.65','--deep-strength','1.10']); assertFile(path.join(out,'convnet','convnet_report.json')); assertFile(path.join(out,'convnet','shallow_convnet_distortion.bmp')); assertFile(path.join(out,'convnet','shallow_convnet_activation_mask.bmp')); assertFile(path.join(out,'convnet','shallow_convnet_activation_overlay.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_distortion.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_activation_mask.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_high_overlay.bmp')); assertFile(path.join(out,'convnet','deeper_convnet_high_overlay_grid.bmp'));
run(['dist/src/cli.js','fit-transform',path.join(out,'convnet','source.bmp'),path.join(out,'convnet','deeper_convnet_distortion.bmp'),'--out',path.join(out,'fit'),'--seed','20260616','--trials','24','--smoothness-weight','0.05','--edge-weight','0.10','--complexity-weight','0.04']); assertFile(path.join(out,'fit','fit_report.json')); assertFile(path.join(out,'fit','fit_trace.json')); assertFile(path.join(out,'fit','fit_support_dictionary.json')); assertFile(path.join(out,'fit','fit_output.bmp')); assertFile(path.join(out,'fit','fit_residual.bmp'));
run(['dist/src/cli.js','segment',path.join(out,'convnet','source.bmp'),'--out',path.join(out,'segment-a'),'--image-id','target_a','--grid','8']); assertFile(path.join(out,'segment-a','segments.json')); assertFile(path.join(out,'segment-a','patch_features.json')); assertFile(path.join(out,'segment-a','patch_labels.json')); assertFile(path.join(out,'segment-a','control_mask.bmp'));
run(['dist/src/cli.js','segment',path.join(out,'convnet','deeper_convnet_distortion.bmp'),'--out',path.join(out,'segment-b'),'--image-id','target_b','--grid','8']); assertFile(path.join(out,'segment-b','segments.json')); assertFile(path.join(out,'segment-b','patch_features.json'));
const labels = { labels: [{ patch_id: 'seg_0000', external_label: 'skin', external_confidence: 0.92, approved_label: 'skin' }, { patch_id: 'seg_0001', external_label: 'garment', external_confidence: 0.88, approved_label: 'garment' }, { patch_id: 'seg_0002', external_label: 'background', external_confidence: 0.81, approved_label: 'background' }] };
const labelsPath=path.join(out,'third_party_labels.json'); fs.writeFileSync(labelsPath,JSON.stringify(labels,null,2));
run(['dist/src/cli.js','import-labels',path.join(out,'segment-a'),labelsPath,'--source-tool','smoke-third-party']); assertFile(path.join(out,'segment-a','training_rows.json'));
run(['dist/src/cli.js','import-labels',path.join(out,'segment-b'),labelsPath,'--source-tool','smoke-third-party']); assertFile(path.join(out,'segment-b','training_rows.json'));
run(['dist/src/cli.js','train-patch-classifier',out,'--out',path.join(out,'classifier')]); assertFile(path.join(out,'classifier','patch_classifier.json'));
run(['dist/src/cli.js','segment-predict',path.join(out,'convnet','source.bmp'),path.join(out,'classifier','patch_classifier.json'),'--out',path.join(out,'predict'),'--grid','8']); assertFile(path.join(out,'predict','patch_scores.json')); assertFile(path.join(out,'predict','part_score_control_mask.bmp'));
run(['dist/src/cli.js','build-targets',out,'--out',path.join(out,'targets'),'--feature','skin_shade','--label','skin']); assertFile(path.join(out,'targets','target_features.json'));
run(['dist/src/cli.js','match-feature',path.join(out,'convnet','source.bmp'),path.join(out,'targets','target_features.json'),'--out',path.join(out,'match'),'--feature','skin_shade','--label','skin','--strength','0.45']); assertFile(path.join(out,'match','match_feature_output.bmp')); assertFile(path.join(out,'match','match_feature_report.json'));
run(['dist/src/cli.js','cartoonify-optimize',path.join(out,'convnet','source.bmp'),'--out',path.join(out,'cartoonify'),'--seed','20260616','--layers','2','--grid','8','--tries','6','--metric','cartoon']); assertFile(path.join(out,'cartoonify','cartoonify_output.bmp')); assertFile(path.join(out,'cartoonify','cartoonify_report.json')); assertFile(path.join(out,'cartoonify','cartoonify_layer_trace.json'));
console.log('image-metrics full annotation, classifier, target, convnet, regularized fit, and cartoonify smoke passed');
