import { Program } from '../core/program';
import { Declaration, ForeignImport, CallExpression } from '../core/ast';

export function emitPython(program: Program): string {
  let out = '# Generated by glc.\n\n';
  for (const mod of program.modules) {
    out += `# Module: ${mod.name}\n\n`;
    for (const item of mod.declarations) {
      if (item.kind === 'ForeignImport') {
        const f = item as ForeignImport;
        const params = f.signature.params.map((_, i) => `arg${i}`).join(', ');
        out += `def ${f.name.name}(${params}):\n`;
        out += `    raise RuntimeError(${JSON.stringify(`foreign cpp symbol ${f.symbol} is not bound in Python output`)})\n\n`;
      }
    }
    for (const item of mod.declarations) {
      if (item.kind === 'Declaration') {
        const d = item as Declaration;
        if (d.value.kind === 'CallExpression') {
          const call = d.value as CallExpression;
          const args = call.arguments.map(a => emitPythonExpr(a)).join(', ');
          out += `${d.name.name} = ${call.callee.name}(${args})\n\n`;
        } else {
          out += `${d.name.name} = ${emitPythonExpr(d.value)}\n\n`;
        }
      }
    }
  }
  return out.trim();
}

function emitPythonExpr(e: any): string {
  if (e.kind === 'Literal') {
    if (typeof e.value === 'boolean') return e.value ? 'True' : 'False';
    return JSON.stringify(e.value);
  }
  if (e.kind === 'Identifier') return e.name;
  if (e.kind === 'CallExpression') {
    const c = e as CallExpression;
    return `${c.callee.name}(${c.arguments.map(emitPythonExpr).join(', ')})`;
  }
  return 'None';
}
